import { useState, type ReactNode } from 'react';
import './SettingsPage.css';
type SettingsTab = 'general' | 'appearance' | 'workspace' | 'canvas' | 'storage' | 'execution' | 'integrations' | 'account';
const tabs: { id: SettingsTab; label: string; icon: string }[] = [
  { id: 'general', label: 'General', icon: '◌' }, { id: 'appearance', label: 'Appearance', icon: '◐' }, { id: 'workspace', label: 'Workspace', icon: '▦' }, { id: 'canvas', label: 'Canvas', icon: '⌘' }, { id: 'storage', label: 'Storage', icon: '□' }, { id: 'execution', label: 'Execution', icon: '▶' }, { id: 'integrations', label: 'Integrations', icon: '↗' }, { id: 'account', label: 'Account', icon: '◎' },
];
function Toggle({ defaultChecked = true }: { defaultChecked?: boolean }) { return <input type="checkbox" defaultChecked={defaultChecked} />; }
function Row({ label, desc, children }: { label: string; desc: string; children: ReactNode }) { return <div className="setting-row"><div><label className="setting-label">{label}</label><p className="setting-desc">{desc}</p></div>{children}</div>; }
export function SettingsPage() {
  const [activeTab, setActiveTab] = useState<SettingsTab>('general'); const [themeMode, setThemeMode] = useState('dark-cyan'); const [autoSave, setAutoSave] = useState(true); const [storagePath, setStoragePath] = useState('C:/Users/SUYASH/.mlflow/workspaces');
  return <div className="settings-page"><div className="settings-header"><div><span className="eyebrow">PREFERENCES</span><h1 className="settings-title">Settings</h1><p className="settings-subtitle">Fine-tune your local ML Flow workspace and execution defaults.</p></div><button className="settings-save">Save changes</button></div><div className="settings-container"><nav className="settings-tabs">{tabs.map((tab) => <button key={tab.id} className={`settings-tab-btn ${activeTab === tab.id ? 'settings-tab-btn--active' : ''}`} onClick={() => setActiveTab(tab.id)}><span>{tab.icon}</span>{tab.label}</button>)}</nav><div className="settings-content">
    {activeTab === 'general' && <section className="settings-section"><h3>General</h3><Row label="Auto-save workflows" desc="Save local canvas changes every 30 seconds."><input type="checkbox" checked={autoSave} onChange={(e) => setAutoSave(e.target.checked)} /></Row><Row label="Start page" desc="Where ML Flow opens when you launch it."><select className="setting-select"><option>Dashboard</option><option>Last workspace</option></select></Row></section>}
    {activeTab === 'appearance' && <section className="settings-section"><h3>Appearance</h3><Row label="Workspace theme" desc="Choose the visual treatment for your interface."><select className="setting-select" value={themeMode} onChange={(e) => setThemeMode(e.target.value)}><option value="dark-cyan">Graphite + mint</option><option value="midnight-violet">Midnight violet</option><option value="deep-space">Deep space</option></select></Row><Row label="Compact controls" desc="Reduce vertical density in toolbars and inspector panels."><Toggle defaultChecked={false} /></Row></section>}
    {activeTab === 'workspace' && <section className="settings-section"><h3>Workspace</h3><Row label="New project template" desc="The starting workflow for a new ML project."><select className="setting-select"><option>Classification benchmark</option><option>Blank workflow</option></select></Row><Row label="Restore previous workspace" desc="Return to your last open project on launch."><Toggle /></Row></section>}
    {activeTab === 'canvas' && <section className="settings-section"><h3>Canvas</h3><Row label="Snap to grid" desc="Align nodes to the 24px workspace grid while dragging."><Toggle /></Row><Row label="Curved connections" desc="Use smooth Bezier paths between workflow nodes."><Toggle /></Row><Row label="Show minimap" desc="Keep a compact map available for large workflows."><Toggle /></Row></section>}
    {activeTab === 'storage' && <section className="settings-section"><h3>Storage</h3><div className="setting-input-group"><label className="setting-label">Local workspace directory</label><input className="setting-text-input" value={storagePath} onChange={(e) => setStoragePath(e.target.value)} /></div><Row label="Cache previews" desc="Keep dataset and chart previews available locally."><Toggle /></Row></section>}
    {activeTab === 'execution' && <section className="settings-section"><h3>Execution</h3><Row label="Default run profile" desc="Applied when a workflow is executed."><select className="setting-select"><option>Local simulation</option><option>Remote runner (coming soon)</option></select></Row><Row label="Keep run history" desc="Store experiment summaries in this workspace."><Toggle /></Row></section>}
    {activeTab === 'integrations' && <section className="settings-section"><h3>Integrations</h3><p className="settings-intro">Connect services when you are ready. Credentials remain local to your device.</p><div className="setting-input-group"><label className="setting-label">Kaggle API token</label><input type="password" className="setting-text-input" placeholder="Paste token to connect" /></div><div className="setting-input-group"><label className="setting-label">Hugging Face token</label><input type="password" className="setting-text-input" placeholder="Paste token to connect" /></div></section>}
    {activeTab === 'account' && <section className="settings-section"><h3>Account</h3><div className="account-card"><div className="account-avatar">AK</div><div><h4>Alex Kumar</h4><p>alexkumar_ml · Community workspace</p></div><span className="license-badge">Active</span></div></section>}
  </div></div></div>;
}
