import { useEffect, useMemo, useState } from 'react';
import { NodeLibrary } from '../../components/NodeLibrary/NodeLibrary';
import { NodeInspector } from '../../components/NodeInspector/NodeInspector';
import { OutputPanel } from '../../components/OutputPanel/OutputPanel';
import { PipelineCanvas } from '../../components/PipelineCanvas/PipelineCanvas';
import { ProjectHeader } from '../../components/ProjectHeader/ProjectHeader';
import { ZoomControls } from '../../components/ZoomControls/ZoomControls';
import { INITIAL_TRAINING_RUNS } from '../../config/constants';
import { MOCK_STARTER_NODES } from '../../config/mockData';
import type { CanvasConnection, CanvasNodeData, Project, TrainingRun } from '../../types';
import './WorkspacePage.css';

interface WorkspacePageProps { project?: Project; }
type LibraryItem={name:string;description:string;type:CanvasNodeData['type']};
export function WorkspacePage({ project }: WorkspacePageProps) {
 const mode=project?.type||'ML'; const starter=useMemo(()=>MOCK_STARTER_NODES[mode].map(n=>({...n,status:n.status==='selected'?'idle':n.status||'idle'})),[mode]);
 const [nodes,setNodes]=useState<CanvasNodeData[]>(starter); const [connections,setConnections]=useState<CanvasConnection[]>(()=>starter.slice(0,-1).map((node,index)=>({id:`link-${node.id}-${starter[index+1].id}`,sourceId:node.id,targetId:starter[index+1].id}))); const [selectedId,setSelectedId]=useState<string>(); const [zoom,setZoom]=useState(.85); const [runs,setRuns]=useState<TrainingRun[]>(INITIAL_TRAINING_RUNS); const [logs,setLogs]=useState<string[]>(['> ML Flow workspace ready.', `> Loaded ${starter.length} pipeline nodes.`]); const [panelHeight,setPanelHeight]=useState(190); const [name,setName]=useState(project?.name||'Customer Churn Prediction v3.1');
 useEffect(()=>{setNodes(starter);setConnections(starter.slice(0,-1).map((n,i)=>({id:`link-${n.id}-${starter[i+1].id}`,sourceId:n.id,targetId:starter[i+1].id})));setSelectedId(undefined);setName(project?.name||'Customer Churn Prediction v3.1')},[project?.id,starter]);
 const selected=nodes.find(n=>n.id===selectedId);
 const move=(id:string,x:number,y:number)=>setNodes(list=>list.map(n=>n.id===id?{...n,x,y}:n));
 const add=(item:LibraryItem,x=130+nodes.length*25,y=140+nodes.length*18)=>{const id=`node-${Date.now()}`;setNodes(list=>[...list,{id,title:item.name,subtitle:item.description,type:item.type,x,y,status:'idle'}]);setSelectedId(id);setLogs(l=>[...l,`> Added ${item.name} to canvas.`]);};
 const connect=(sourceId:string,targetId:string)=>{const source=nodes.find(n=>n.id===sourceId),target=nodes.find(n=>n.id===targetId);if(!source||!target||source.type==='eval'||target.type==='input'){setLogs(l=>[...l,'! Those node ports are not compatible.']);return;}setConnections(list=>list.some(c=>c.sourceId===sourceId&&c.targetId===targetId)?list:[...list,{id:`link-${sourceId}-${targetId}`,sourceId,targetId}]);};
 const execute=async(flow:boolean)=>{const ordered:string[]=[];const visit=(id:string,seen=new Set<string>())=>{if(seen.has(id))return;seen.add(id);connections.filter(c=>c.targetId===id).forEach(c=>visit(c.sourceId,seen));if(!ordered.includes(id))ordered.push(id)};if(flow)nodes.forEach(n=>visit(n.id));else if(selectedId)visit(selectedId);const queue=ordered;if(!queue.length){setLogs(l=>[...l,'! Select a node to run it.']);return;} setLogs(l=>[...l,`> ${flow?'Running complete flow':'Running current node and upstream dependencies'}…`]); for(const id of queue){setNodes(list=>list.map(n=>n.id===id?{...n,status:'running'}:n));setLogs(l=>[...l,`  • ${nodes.find(n=>n.id===id)?.title||id}: running`]);await new Promise<void>(resolve=>window.setTimeout(resolve,420));setNodes(list=>list.map(n=>n.id===id?{...n,status:'success'}:n));setLogs(l=>[...l,`  ✓ ${nodes.find(n=>n.id===id)?.title||id}: complete`]);}const model=selected?.title||nodes.find(n=>n.type==='model')?.title||'Pipeline';setRuns(list=>[{id:`Run #${112+list.length}`,model,accuracy:.87,f1Score:.84,trainingTime:`${Math.max(1,Math.round(queue.length*.4))}s`,status:'Completed'},...list]);setLogs(l=>[...l,`> Run complete — ${queue.length} node${queue.length===1?'':'s'} succeeded.`]);};
 const menuAction=(action:string)=>{if(action==='Reset workspace'){setNodes([]);setConnections([]);setSelectedId(undefined);setLogs(l=>[...l,'> Workspace cleared.']);}else setLogs(l=>[...l,`> ${action} requested.`]);};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'&&selected){e.preventDefault();add({name:`${selected.title} copy`,description:selected.subtitle,type:selected.type},selected.x+36,selected.y+36)}if((e.key==='Delete'||e.key==='Backspace')&&selected&&!(e.target instanceof HTMLInputElement)){setNodes(list=>list.filter(n=>n.id!==selected.id));setConnections(list=>list.filter(c=>c.sourceId!==selected.id&&c.targetId!==selected.id));setSelectedId(undefined)}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();execute(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)} ,[selected,nodes,connections]);
 const removeSelected=()=>{if(!selected)return;setNodes(list=>list.filter(node=>node.id!==selected.id));setConnections(list=>list.filter(connection=>connection.sourceId!==selected.id&&connection.targetId!==selected.id));setSelectedId(undefined);setLogs(log=>[...log,`> Removed ${selected.title}.`]);};
 const disconnectSelected=()=>{if(!selected)return;setConnections(list=>list.filter(connection=>connection.sourceId!==selected.id&&connection.targetId!==selected.id));setLogs(log=>[...log,`> Disconnected ${selected.title}.`]);};
 return <div className="workspace-page"><ProjectHeader project={project} name={name} onNameChange={setName} onRunNode={()=>execute(false)} onRunFlow={()=>execute(true)} canRunNode={Boolean(selected)} onAction={menuAction}/><div className="workspace-page__body"><NodeLibrary onAdd={item=>add(item)}/><section className="workspace-page__canvas"><PipelineCanvas nodes={nodes} connections={connections} selectedId={selectedId} zoom={zoom} onSelect={setSelectedId} onMove={move} onAdd={add} onConnect={connect} onDisconnect={id=>{setConnections(list=>list.filter(connection=>connection.id!==id));setLogs(log=>[...log,'> Connection removed.']);}} onZoom={setZoom}/><NodeInspector node={selected} onClose={()=>setSelectedId(undefined)} onRun={()=>execute(false)} onDelete={removeSelected} onDisconnect={disconnectSelected}/><ZoomControls zoom={zoom} onChange={setZoom} onFit={()=>setZoom(.85)}/></section></div><OutputPanel nodes={nodes} runs={runs} logs={logs} height={panelHeight} onResize={setPanelHeight}/></div>;
}
