import type {
  PostItem,
  CountryMemberPin,
  WeeklyChallenge,
  MentorMatch,
  TrendingItem,
} from '../types';

export const MOCK_POSTS: PostItem[] = [
  {
    id: 'post-1',
    authorName: 'Alex Kumar',
    authorHandle: '@alexkumar_ml',
    authorAvatar: 'AK',
    authorRole: 'Senior ML Engineer',
    authorCountry: 'India',
    authorFlag: '🇮🇳',
    timestamp: '15 mins ago',
    mode: 'project',
    textContent:
      'Just deployed a visual ResNet-18 Deep Convolutional pipeline on ML Flow! Optimized learning rates using Cosine Annealing and achieved 94.2% top-1 validation accuracy. Check out the model structure and feel free to fork it below.',
    tags: ['ResNet', 'DeepLearning', 'PyTorch', 'ComputerVision'],
    attachedProject: {
      id: 'proj-3',
      name: 'ResNet Image Classifier',
      datasetName: 'cifar_subset.parquet',
      taskType: 'Computer Vision',
      metricAchieved: '94.2% Acc',
      nodesCount: 8,
    },
    likesCount: 42,
    commentsCount: 9,
    forksCount: 14,
    liked: true,
    saved: true,
    comments: [
      {
        id: 'c-1',
        authorName: 'Sarah Chen',
        authorHandle: '@sarah_ai',
        authorAvatar: 'SC',
        content: 'Impressive convergence speed! Did you apply Mixup data augmentation?',
        timestamp: '10 mins ago',
      },
      {
        id: 'c-2',
        authorName: 'Alex Kumar',
        authorHandle: '@alexkumar_ml',
        authorAvatar: 'AK',
        content: 'Yes! Combined RandomCrop with Mixup (alpha=0.2). It boosted generalization by 1.8%.',
        timestamp: '5 mins ago',
      },
    ],
  },
  {
    id: 'post-2',
    authorName: 'Dr. Marcus Vance',
    authorHandle: '@marcus_vance',
    authorAvatar: 'MV',
    authorRole: 'Lead Data Scientist',
    authorCountry: 'Germany',
    authorFlag: '🇩🇪',
    timestamp: '1 hour ago',
    mode: 'question',
    textContent:
      'When working with highly imbalanced financial datasets (e.g., 0.17% positive cases), do you prefer scale_pos_weight in XGBoost or synthetic oversampling (SMOTE) before feature scaling? Curious about your experience in production.',
    tags: ['XGBoost', 'ImbalancedData', 'FraudDetection', 'EDA'],
    codeSnippet: `# XGBoost scale_pos_weight calculation
ratio = float(np.sum(y_train == 0)) / np.sum(y_train == 1)
model = XGBClassifier(scale_pos_weight=ratio, eval_metric='aucpr')`,
    likesCount: 28,
    commentsCount: 14,
    saved: false,
    comments: [
      {
        id: 'c-3',
        authorName: 'Elena Rostova',
        authorHandle: '@elena_data',
        authorAvatar: 'ER',
        content:
          'scale_pos_weight is almost always better in practice! SMOTE can create noise along non-linear decision boundaries.',
        timestamp: '45 mins ago',
      },
    ],
  },
  {
    id: 'post-3',
    authorName: 'Sarah Chen',
    authorHandle: '@sarah_ai',
    authorAvatar: 'SC',
    authorRole: 'AI Research Lead',
    authorCountry: 'United States',
    authorFlag: '🇺🇸',
    timestamp: '3 hours ago',
    mode: 'resource',
    textContent:
      'Curated an intuitive breakdown of Bayesian Optimization vs. Hyperparameter Grid Search! Essential reading for anyone tuning complex Random Forest or LightGBM pipelines without wasting GPU hours.',
    tags: ['Hyperparameters', 'AutoML', 'BayesianOpt', 'Optimization'],
    linkPreview: {
      title: 'Practical Guide to Bayesian Optimization & Gaussian Processes in ML',
      domain: 'towardsdatascience.com',
      description:
        'Learn how acquisition functions like Expected Improvement (EI) navigate hyperparameter spaces 5x faster than random search.',
      url: 'https://towardsdatascience.com',
      thumbnailUrl: '📊',
    },
    likesCount: 89,
    commentsCount: 6,
    forksCount: 31,
    liked: false,
    saved: true,
  },
  {
    id: 'post-4',
    authorName: 'Dev Patel',
    authorHandle: '@devp_ml',
    authorAvatar: 'DP',
    authorRole: 'AI Architect',
    authorCountry: 'United Kingdom',
    authorFlag: '🇬🇧',
    timestamp: '5 hours ago',
    mode: 'thought',
    textContent:
      'Golden rule of ML pipeline hygiene: NEVER fit feature scalers or missing value imputers on the entire dataset before train/test splitting! Always fit on training folds ONLY, then transform validation folds. Prevent data leakage early.',
    tags: ['DataHygiene', 'DataLeakage', 'BestPractices', 'MLPointers'],
    likesCount: 114,
    commentsCount: 19,
    saved: true,
  },
  {
    id: 'post-5',
    authorName: 'Elena Rostova',
    authorHandle: '@elena_data',
    authorAvatar: 'ER',
    authorRole: 'Senior EDA Specialist',
    authorCountry: 'Japan',
    authorFlag: '🇯🇵',
    timestamp: 'Yesterday',
    mode: 'project',
    textContent:
      'Finished an extensive Exploratory Data Analysis & Customer Segmentation workflow attached to e-commerce transaction logs. Uncovered 4 distinct cluster personas using K-Means & PCA visualizations!',
    tags: ['ClusterAnalysis', 'KMeans', 'CustomerSegmentation', 'EDA'],
    attachedProject: {
      id: 'proj-2',
      name: 'E-commerce EDA & Segmentation',
      datasetName: 'ecommerce_behavior.csv',
      taskType: 'Clustering',
      metricAchieved: 'Silhouette 0.68',
      nodesCount: 5,
    },
    likesCount: 67,
    commentsCount: 8,
    forksCount: 22,
    liked: true,
  },
];

export const MOCK_COUNTRY_MAP_PINS: CountryMemberPin[] = [
  {
    countryCode: 'IN',
    countryName: 'India',
    flag: '🇮🇳',
    xPercent: 71,
    yPercent: 48,
    memberCount: 4150,
    topMembers: [
      { name: 'Alex Kumar', avatar: 'AK', role: 'Senior ML Engineer' },
      { name: 'Dev Patel', avatar: 'DP', role: 'AI Architect' },
      { name: 'Priya Sharma', avatar: 'PS', role: 'Data Scientist' },
    ],
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    flag: '🇺🇸',
    xPercent: 22,
    yPercent: 36,
    memberCount: 3420,
    topMembers: [
      { name: 'Sarah Chen', avatar: 'SC', role: 'AI Research Lead' },
      { name: 'Michael Scott', avatar: 'MS', role: 'MLOps Lead' },
    ],
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    flag: '🇩🇪',
    xPercent: 49,
    yPercent: 28,
    memberCount: 1280,
    topMembers: [{ name: 'Dr. Marcus Vance', avatar: 'MV', role: 'Lead Data Scientist' }],
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    xPercent: 46,
    yPercent: 25,
    memberCount: 950,
    topMembers: [{ name: 'Arthur Pendelton', avatar: 'AP', role: 'NLP Specialist' }],
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    flag: '🇯🇵',
    xPercent: 84,
    yPercent: 38,
    memberCount: 760,
    topMembers: [{ name: 'Elena Rostova', avatar: 'ER', role: 'Senior EDA Specialist' }],
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    flag: '🇧🇷',
    xPercent: 35,
    yPercent: 68,
    memberCount: 840,
    topMembers: [{ name: 'Lucas Silva', avatar: 'LS', role: 'Deep Learning Dev' }],
  },
];

export const MOCK_WEEKLY_CHALLENGE: WeeklyChallenge = {
  id: 'challenge-aug-2026',
  title: 'Credit Card Fraud Detection Challenge 💳',
  datasetName: 'creditcard_fraud_unbalanced.csv',
  description:
    'Build an end-to-end ML Flow pipeline to maximize PR-AUC score on highly imbalanced transaction logs (284,807 transactions).',
  deadline: '3 days left',
  participantsCount: 428,
  prize: '1,500 Karma + Gold AutoML Badge',
  leaderboard: [
    { rank: 1, name: 'Sarah Chen', avatar: 'SC', score: '0.942 PR-AUC', metric: 'XGBoost + SMOTE' },
    { rank: 2, name: 'Alex Kumar', avatar: 'AK', score: '0.938 PR-AUC', metric: 'Random Forest' },
    { rank: 3, name: 'Dr. Marcus Vance', avatar: 'MV', score: '0.925 PR-AUC', metric: 'LightGBM' },
  ],
};

export const MOCK_MENTOR_MATCHES: MentorMatch[] = [
  {
    id: 'm-1',
    name: 'Sarah Chen',
    handle: '@sarah_ai',
    avatar: 'SC',
    role: 'AI Research Lead',
    skills: ['PyTorch', 'Transformers', 'Computer Vision'],
    timezone: 'PST (GMT-7)',
    matchReason: 'Shares your interest in Deep Learning & ResNet architectures',
    matchPercentage: 98,
  },
  {
    id: 'm-2',
    name: 'Dr. Marcus Vance',
    handle: '@marcus_vance',
    avatar: 'MV',
    role: 'Lead Data Scientist',
    skills: ['Time Series', 'XGBoost', 'Scikit-Learn'],
    timezone: 'CET (GMT+2)',
    matchReason: 'Top contributor in Classification & Imbalanced Data',
    matchPercentage: 94,
  },
  {
    id: 'm-3',
    name: 'Elena Rostova',
    handle: '@elena_data',
    avatar: 'ER',
    role: 'Senior EDA Specialist',
    skills: ['Feature Engineering', 'Data Cleaning', 'Seaborn'],
    timezone: 'JST (GMT+9)',
    matchReason: 'Expert in Exploratory Data Analysis & Outlier Profiling',
    matchPercentage: 91,
  },
];

export const MOCK_TRENDING_ITEMS: TrendingItem[] = [
  { id: 't-1', name: 'XGBoost Classifier', category: 'Algorithm', usageCount: 14200, growth: '+18%' },
  { id: 't-2', name: 'Random Forest Ensemble', category: 'Algorithm', usageCount: 11800, growth: '+12%' },
  { id: 't-3', name: 'ResNet-18 Deep ConvNet', category: 'Pipeline Template', usageCount: 8400, growth: '+35%' },
  { id: 't-4', name: 'Missing Value KNN Imputer', category: 'Algorithm', usageCount: 7100, growth: '+9%' },
  { id: 't-5', name: 'SHAP Feature Explainer', category: 'Pipeline Template', usageCount: 5900, growth: '+24%' },
];

export const MOCK_SUGGESTED_USERS = [
  { id: 'u-1', name: 'Sofia Rodriguez', handle: '@sofia_ml', avatar: 'SR', role: 'Kaggle Grandmaster', followers: '12.4k' },
  { id: 'u-2', name: 'Dev Patel', handle: '@devp_ml', avatar: 'DP', role: 'AI Architect', followers: '8.9k' },
  { id: 'u-3', name: 'Lucas Silva', handle: '@lucas_ai', avatar: 'LS', role: 'DL Researcher', followers: '5.2k' },
];
