import type { EncyclopediaCardData, LearningStage } from '../types';

export const ML_STAGES: LearningStage[] = [
  {
    id: 'foundations',
    title: 'Stage 1: Supervised Regression & Linear Models',
    subtitle: 'Master parametric algorithms, linear boundaries, and regularization',
    modules: [
      { id: 'ml-m1', title: 'Linear Regression & OLS', estimatedMinutes: 15, difficulty: 'Beginner', completed: true, locked: false, category: 'ML', stageId: 'foundations', encyclopediaId: 'ml-linear-regression' },
      { id: 'ml-m2', title: 'Ridge & Lasso Regularization', estimatedMinutes: 18, difficulty: 'Beginner', completed: true, locked: false, category: 'ML', stageId: 'foundations', encyclopediaId: 'ml-ridge-lasso' },
      { id: 'ml-m3', title: 'Logistic Regression', estimatedMinutes: 16, difficulty: 'Beginner', completed: true, locked: false, category: 'ML', stageId: 'foundations', encyclopediaId: 'ml-logistic-regression' },
      { id: 'ml-m4', title: 'K-Nearest Neighbors (KNN)', estimatedMinutes: 14, difficulty: 'Beginner', completed: false, locked: false, category: 'ML', stageId: 'foundations', encyclopediaId: 'ml-knn' },
    ],
  },
  {
    id: 'core',
    title: 'Stage 2: Tree-Based Models & Ensembles',
    subtitle: 'From Decision Trees to state-of-the-art Gradient Boosting (XGBoost/LightGBM/CatBoost)',
    modules: [
      { id: 'ml-m5', title: 'Decision Trees (Gini & Entropy)', estimatedMinutes: 18, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'core', encyclopediaId: 'ml-decision-trees' },
      { id: 'ml-m6', title: 'Random Forest Classifier', estimatedMinutes: 20, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'core', encyclopediaId: 'ml-random-forest' },
      { id: 'ml-m7', title: 'AdaBoost & Gradient Boosting', estimatedMinutes: 22, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'core', encyclopediaId: 'ml-gradient-boosting' },
      { id: 'ml-m8', title: 'XGBoost, LightGBM & CatBoost', estimatedMinutes: 25, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'core', encyclopediaId: 'ml-xgboost' },
    ],
  },
  {
    id: 'eval_tuning',
    title: 'Stage 3: Model Evaluation & Hyperparameter Tuning',
    subtitle: 'Validate generalization, prevent overfitting, and optimize parameters',
    modules: [
      { id: 'ml-m9', title: 'Cross-Validation & Train-Test Split', estimatedMinutes: 15, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'eval_tuning', encyclopediaId: 'ml-cross-validation' },
      { id: 'ml-m10', title: 'ROC-AUC, Confusion Matrix & F1-Score', estimatedMinutes: 18, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'eval_tuning', encyclopediaId: 'ml-evaluation-metrics' },
      { id: 'ml-m11', title: 'Bias-Variance Tradeoff', estimatedMinutes: 15, difficulty: 'Practitioner', completed: false, locked: false, category: 'ML', stageId: 'eval_tuning', encyclopediaId: 'ml-bias-variance' },
      { id: 'ml-m12', title: 'Grid, Random & Bayesian Tuning', estimatedMinutes: 24, difficulty: 'Expert', completed: false, locked: false, category: 'ML', stageId: 'eval_tuning', encyclopediaId: 'ml-hyperparameter-tuning' },
    ],
  },
  {
    id: 'advanced',
    title: 'Stage 4: Unsupervised Learning & Dimensionality Reduction',
    subtitle: 'Cluster unlabelled data and compress high-dimensional feature spaces',
    modules: [
      { id: 'ml-m13', title: 'K-Means & Hierarchical Clustering', estimatedMinutes: 20, difficulty: 'Expert', completed: false, locked: true, category: 'ML', stageId: 'advanced', encyclopediaId: 'ml-kmeans' },
      { id: 'ml-m14', title: 'DBSCAN Density Clustering', estimatedMinutes: 18, difficulty: 'Expert', completed: false, locked: true, category: 'ML', stageId: 'advanced', encyclopediaId: 'ml-dbscan' },
      { id: 'ml-m15', title: 'Support Vector Machines (SVM)', estimatedMinutes: 22, difficulty: 'Expert', completed: false, locked: true, category: 'ML', stageId: 'advanced', encyclopediaId: 'ml-svm' },
      { id: 'ml-m16', title: 'Principal Component Analysis (PCA)', estimatedMinutes: 22, difficulty: 'Expert', completed: false, locked: true, category: 'ML', stageId: 'advanced', encyclopediaId: 'ml-pca' },
    ],
  },
];

export const ML_ENCYCLOPEDIA_CARDS: EncyclopediaCardData[] = [
  {
    id: 'ml-linear-regression',
    title: 'Linear Regression & OLS',
    category: 'ML',
    difficulty: 'Beginner',
    stageId: 'foundations',
    shortSummary: 'Model continuous relationships by fitting an Ordinary Least Squares (OLS) line.',
    icon: '📉',
    tags: ['Regression', 'OLS', 'MSE', 'Linear'],
    content: {
      whatItIs: 'Linear Regression predicts a continuous numeric target variable by fitting a straight line (or hyperplane) through data points.',
      whyItExists: 'It is the fundamental baseline model for continuous outcomes, offering high interpretability and instant training speeds.',
      howItWorks: {
        steps: [
          'Formulate line equation: y = w1*x1 + w2*x2 + ... + b.',
          'Calculate Residual Sum of Squares (RSS) / Mean Squared Error (MSE).',
          'Solve for optimal weights using Ordinary Least Squares closed-form equation or Gradient Descent.',
        ],
        mathFormula: 'y = X w + b, \\quad L(w) = \\frac{1}{2n} \\|X w - y\\|^2',
        visualDiagramText: '[ Data Points ] ➔ [ Minimize Sum of Squared Errors ] ➔ [ Best Fit Line ]',
      },
      whenToUse: {
        useCases: ['Predicting house prices, sales forecasting, linear trend analysis.'],
        avoidWhen: ['Relationships are highly non-linear or feature count >> sample count.'],
        alternatives: ['Polynomial Regression', 'Random Forest Regressor', 'XGBoost Regressor'],
      },
      pitfalls: ['Sensitive to severe outliers that pull the regression line away from the median distribution.'],
      playground: {
        title: 'Linear Slope & Intercept Simulator',
        description: 'Adjust noise level and slope coefficient to see MSE error update live.',
        params: [
          { name: 'slope', label: 'True Slope (w)', min: -5, max: 5, step: 0.5, defaultValue: 1.5, description: 'True underlying linear coefficient.' },
          { name: 'noise', label: 'Gaussian Noise (σ)', min: 0, max: 10, step: 1, defaultValue: 2, description: 'Standard deviation of random error.' },
        ],
        chartType: 'regression',
      },
      realProjectCTA: { label: 'Build Linear Regression Workspace', templateType: 'ML' },
    },
  },
  {
    id: 'ml-ridge-lasso',
    title: 'Ridge & Lasso Regularization',
    category: 'ML',
    difficulty: 'Beginner',
    stageId: 'foundations',
    shortSummary: 'Prevent overfitting via L2 (Ridge) weight shrinking and L1 (Lasso) feature selection.',
    icon: '🎛️',
    tags: ['Regularization', 'L1', 'L2', 'Sparsity'],
    content: {
      whatItIs: 'Ridge (L2) and Lasso (L1) regression add penalty terms to the OLS loss function to constrain model complexity and control weight magnitudes.',
      whyItExists: 'Standard linear regression overfits when features are highly correlated or numerous. Regularization penalizes large weight coefficients.',
      howItWorks: {
        steps: [
          'Ridge (L2): Adds sum of squared weights penalty (alpha * ||w||^2). Shrinks weights smoothly toward zero.',
          'Lasso (L1): Adds sum of absolute weights penalty (alpha * ||w||). Forces uninformative weights exactly to ZERO (feature selection!).',
          'ElasticNet: Combines both L1 and L2 penalties.',
        ],
        mathFormula: 'L_{\\text{Ridge}} = \\text{MSE} + \\alpha \\sum w_j^2, \\quad L_{\\text{Lasso}} = \\text{MSE} + \\alpha \\sum |w_j|',
        visualDiagramText: '[ Overfitted Weights ] ➔ [ Apply L1/L2 Alpha Penalty ] ➔ [ Regularized Sparse Model ]',
      },
      whenToUse: {
        useCases: ['Datasets with hundreds of features or high multicollinearity.'],
        avoidWhen: ['Non-linear relationships (prefer tree ensembles).'],
        alternatives: ['ElasticNet', 'LGBM Regressor'],
      },
      pitfalls: ['Forgetting to scale features before applying L1/L2 penalties.'],
      playground: {
        title: 'Alpha Penalty Strength Tuner',
        description: 'Adjust alpha regularization parameter to observe weight shrinking.',
        params: [
          { name: 'alpha', label: 'Penalty Strength (α)', min: 0.01, max: 10, step: 0.5, defaultValue: 1.0, description: 'Higher alpha increases regularization.' },
        ],
        chartType: 'regression',
      },
      realProjectCTA: { label: 'Add Regularized Regression Node', templateType: 'ML' },
    },
  },
  {
    id: 'ml-logistic-regression',
    title: 'Logistic Regression',
    category: 'ML',
    difficulty: 'Beginner',
    stageId: 'foundations',
    shortSummary: 'Binary & multi-class classification using Sigmoid probability decision boundaries.',
    icon: '⚖️',
    tags: ['Classification', 'Sigmoid', 'Binary', 'LogLoss'],
    content: {
      whatItIs: 'Logistic Regression maps linear combinations of inputs through a Sigmoid activation function to output probabilities between 0 and 1.',
      whyItExists: 'It is the standard baseline algorithm for binary classification tasks, yielding clear calibrated probability scores.',
      howItWorks: {
        steps: [
          'Calculate linear score z = w^T x + b.',
          'Pass through Sigmoid function σ(z) = 1 / (1 + e^-z).',
          'Optimize Binary Cross-Entropy (Log Loss) via Gradient Descent.',
        ],
        mathFormula: '\\sigma(z) = \\frac{1}{1 + e^{-z}}, \\quad \\text{Loss} = -\\sum [y \\ln(\\hat{y}) + (1-y)\\ln(1-\\hat{y})]',
        visualDiagramText: '[ Linear Score z ] ➔ [ Sigmoid S-Curve ] ➔ [ Probability P(Y=1) ]',
      },
      whenToUse: {
        useCases: ['Telecom churn, medical diagnosis, credit default probability.'],
        avoidWhen: ['Complex non-linear decision boundaries.'],
        alternatives: ['Random Forest Classifier', 'XGBoost Classifier'],
      },
      pitfalls: ['Using default 0.5 decision threshold when classes are heavily imbalanced.'],
      playground: {
        title: 'Sigmoid Decision Boundary Tuner',
        description: 'Adjust decision threshold to see Precision-Recall trade-off.',
        params: [
          { name: 'threshold', label: 'Decision Threshold', min: 0.1, max: 0.9, step: 0.05, defaultValue: 0.5, description: 'Probability cut-off for positive class prediction.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Build Logistic Classification Pipeline', templateType: 'ML' },
    },
  },
  {
    id: 'ml-knn',
    title: 'K-Nearest Neighbors (KNN)',
    category: 'ML',
    difficulty: 'Beginner',
    stageId: 'foundations',
    shortSummary: 'Instance-based non-parametric classification & regression based on spatial distance.',
    icon: '📍',
    tags: ['KNN', 'Euclidean', 'Distance', 'InstanceBased'],
    content: {
      whatItIs: 'KNN classifies unknown data points by taking a majority vote among its K nearest neighbors in vector space.',
      whyItExists: 'It requires zero training time (lazy learner) and naturally captures non-linear local decision boundaries.',
      howItWorks: {
        steps: [
          'Store all training samples in memory.',
          'For a new query point, compute distance (Euclidean, Manhattan) to all training samples.',
          'Identify top K closest neighbors and return majority class vote.',
        ],
        mathFormula: 'd(x, y) = \\sqrt{\\sum_{i=1}^n (x_i - y_i)^2}',
        visualDiagramText: '[ Query Point ] ➔ [ Find K=5 Nearest Neighbors ] ➔ [ Majority Class Vote ]',
      },
      whenToUse: {
        useCases: ['Small to medium datasets, recommendation baselines, spatial lookup.'],
        avoidWhen: ['Large datasets (>100k rows) due to expensive O(N) inference time per query.'],
        alternatives: ['RadiusNeighbors', 'Annoy / FAISS for fast approximate search'],
      },
      pitfalls: ['Extremely sensitive to unscaled feature magnitudes and curse of dimensionality.'],
      playground: {
        title: 'K-Neighbors Spatial Decision Boundary',
        description: 'Adjust K value to see boundary smoothing.',
        params: [
          { name: 'neighborsK', label: 'Neighbors (K)', min: 1, max: 25, step: 2, defaultValue: 5, description: 'Number of neighbors involved in decision voting.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Train KNN Model Node', templateType: 'ML' },
    },
  },
  {
    id: 'ml-decision-trees',
    title: 'Decision Trees (Gini & Entropy)',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'core',
    shortSummary: 'Hierarchical rule-based splitting optimizing Gini Impurity or Information Gain.',
    icon: '🌳',
    tags: ['DecisionTree', 'Gini', 'Entropy', 'RuleBased'],
    content: {
      whatItIs: 'Decision Trees recursively partition feature space into axis-aligned rectangular regions based on feature split rules.',
      whyItExists: 'They are completely interpretable, handle non-linear relationships naturally, and require no feature scaling.',
      howItWorks: {
        steps: [
          'Evaluate potential splits for every feature using Gini Impurity or Information Gain (Entropy).',
          'Select split yielding highest purity gain.',
          'Repeat recursively until max_depth or min_samples_split threshold is reached.',
        ],
        mathFormula: '\\text{Gini} = 1 - \\sum p_i^2, \\quad \\text{Entropy} = -\\sum p_i \\log_2(p_i)',
        visualDiagramText: '[ Root Node: Income > $50k ] ➔ YES/NO ➔ [ Leaf Decision Nodes ]',
      },
      whenToUse: {
        useCases: ['Exploratory rule discovery, decision logic auditing.'],
        avoidWhen: ['Standalone usage on noisy data (high variance, prone to severe overfitting).'],
        alternatives: ['Random Forest', 'XGBoost'],
      },
      pitfalls: ['Allowing unconstrained max_depth creates memorized leaves with 100% training accuracy.'],
      playground: {
        title: 'Tree Max Depth & Variance Simulator',
        description: 'Adjust max_depth to observe overfitting on decision boundaries.',
        params: [
          { name: 'maxDepth', label: 'Max Tree Depth', min: 1, max: 15, step: 1, defaultValue: 4, description: 'Maximum depth allowed for split hierarchy.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Build Decision Tree Pipeline', templateType: 'ML' },
    },
  },
  {
    id: 'ml-random-forest',
    title: 'Random Forest Classifier',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'core',
    shortSummary: 'Ensemble bagging of decorrelated decision trees with feature sub-sampling.',
    icon: '🌲',
    tags: ['RandomForest', 'Ensemble', 'Bagging', 'FeatureImportance'],
    content: {
      whatItIs: 'Random Forest builds an ensemble of dozens or hundreds of decision trees trained on bootstrap samples with random feature subsets.',
      whyItExists: 'It dramatically reduces variance compared to a single decision tree while maintaining strong predictive performance.',
      howItWorks: {
        steps: [
          'Bootstrap Sampling (Bagging): Create N dataset subsets with replacement.',
          'Feature Sub-sampling: At each node split, consider only sqrt(M) random features.',
          'Aggregate individual tree predictions by majority voting.',
        ],
        mathFormula: '\\hat{f}_{rf}^B(x) = \\frac{1}{B} \\sum_{b=1}^B T_b(x)',
        visualDiagramText: '[ 100 Decorrelated Trees ] ➔ [ Parallel Predictions ] ➔ [ Majority Vote Output ]',
      },
      whenToUse: {
        useCases: ['Tabular classification & regression baseline benchmark for structured data.'],
        avoidWhen: ['Ultra-low latency edge deployments where memory footprint is constrained.'],
        alternatives: ['XGBoost', 'ExtraTreesClassifier'],
      },
      pitfalls: ['Ignoring out-of-bag (OOB) validation score capabilities.'],
      playground: {
        title: 'Forest Size (n_estimators) Tuner',
        description: 'Adjust number of trees to observe variance reduction.',
        params: [
          { name: 'nEstimators', label: 'Number of Trees (n_estimators)', min: 10, max: 200, step: 10, defaultValue: 100, description: 'Total decision trees in forest ensemble.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Deploy Random Forest Model', templateType: 'ML' },
    },
  },
  {
    id: 'ml-gradient-boosting',
    title: 'AdaBoost & Gradient Boosting',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'core',
    shortSummary: 'Sequential boosting where weak learners sequentially correct previous residual errors.',
    icon: '⚡',
    tags: ['Boosting', 'GBDT', 'AdaBoost', 'Residuals'],
    content: {
      whatItIs: 'Gradient Boosting builds trees sequentially, where each new tree is trained to predict the residual errors (gradients) of all prior trees combined.',
      whyItExists: 'Sequential residual fitting yields higher peak predictive accuracy than parallel bagging methods on structured tabular data.',
      howItWorks: {
        steps: [
          'Fit initial base model (e.g. constant mean value).',
          'Calculate pseudo-residuals (negative gradient of loss function).',
          'Fit new decision tree to pseudo-residuals and update ensemble with learning rate scale factor.',
        ],
        mathFormula: 'F_m(x) = F_{m-1}(x) + \\eta \\cdot h_m(x)',
        visualDiagramText: '[ Initial Model ] ➔ Calculate Residuals ➔ [ Fit Tree to Errors ] ➔ [ Update Ensemble ]',
      },
      whenToUse: {
        useCases: ['Competitive Kaggle tabular datasets, credit scoring, CTR prediction.'],
        avoidWhen: ['Unstructured image pixels or raw audio (use CNNs/Transformers).'],
        alternatives: ['XGBoost', 'LightGBM', 'CatBoost'],
      },
      pitfalls: ['High learning rate with high tree count causing fast overfitting.'],
      playground: {
        title: 'Learning Rate Shrinkage Simulator',
        description: 'Adjust learning rate eta to see residual convergence curves.',
        params: [
          { name: 'learningRate', label: 'Learning Rate (η)', min: 0.01, max: 0.5, step: 0.02, defaultValue: 0.1, description: 'Step size shrinkage applied to each new tree.' },
        ],
        chartType: 'regression',
      },
      realProjectCTA: { label: 'Build Gradient Boosting Flow', templateType: 'ML' },
    },
  },
  {
    id: 'ml-xgboost',
    title: 'XGBoost, LightGBM & CatBoost',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'core',
    shortSummary: 'High-performance regularized GBDT engines with histogram binning and categorical support.',
    icon: '🚀',
    tags: ['XGBoost', 'LightGBM', 'CatBoost', 'KaggleFav'],
    content: {
      whatItIs: 'Production-grade gradient boosted decision tree frameworks optimized for speed, hardware acceleration, second-order Taylor expansion, and sparse handling.',
      whyItExists: 'XGBoost, LightGBM, and CatBoost dominate competitive tabular ML by handling millions of rows in seconds with built-in regularization.',
      howItWorks: {
        steps: [
          'XGBoost: Uses second-order gradients (Hessian) + L1/L2 tree leaf regularization.',
          'LightGBM: Histogram binning + Leaf-wise (best-first) tree growth for 10x speed.',
          'CatBoost: Ordered target statistics preventing target leakage in categorical columns.',
        ],
        mathFormula: 'Obj^{(t)} = \\sum [g_i f_t(x_i) + \\frac{1}{2} h_i f_t^2(x_i)] + \\gamma T + \\frac{1}{2} \\lambda \\sum w_j^2',
        visualDiagramText: '[ Tabular Data ] ➔ [ Second-Order Hessian Split ] ➔ [ Regularized Leaf Trees ]',
      },
      whenToUse: {
        useCases: ['Industry tabular classification, ranking, regression benchmarks.'],
        avoidWhen: ['Tiny datasets (<100 rows) where simple Logistic Regression suffices.'],
        alternatives: ['Random Forest', 'TabNet'],
      },
      pitfalls: ['Not tuning max_depth and min_child_weight leads to severe overfitting.'],
      playground: {
        title: 'XGBoost Regularization & Speed Tuner',
        description: 'Adjust tree depth and subsample ratio to inspect accuracy curves.',
        params: [
          { name: 'maxDepth', label: 'Max Tree Depth', min: 2, max: 12, step: 1, defaultValue: 6, description: 'Maximum depth per gradient boosted tree.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Launch XGBoost Pipeline Workspace', templateType: 'ML' },
    },
  },
  {
    id: 'ml-cross-validation',
    title: 'Cross-Validation & Train-Test Split',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'eval_tuning',
    shortSummary: 'Stratified K-Fold validation strategies preventing optimistic holdout bias.',
    icon: '🔁',
    tags: ['KFold', 'Stratified', 'CrossValidation', 'Validation'],
    content: {
      whatItIs: 'Cross-validation splits dataset into K folds, iteratively training on K-1 folds and testing on the remaining fold to compute out-of-sample metrics.',
      whyItExists: 'A single train/test split can be lucky or unlucky. K-Fold provides unbiased mean performance and variance estimates.',
      howItWorks: {
        steps: [
          'Stratified K-Fold: Ensures class label proportions are preserved in every fold.',
          'Train model on K-1 folds, calculate score on validation fold.',
          'Repeat K times and report mean ± standard deviation validation score.',
        ],
        visualDiagramText: '[ Fold 1 | Fold 2 | Fold 3 | Fold 4 | Fold 5 ] ➔ Rotate Validation Fold x5',
      },
      whenToUse: {
        useCases: ['All tabular ML model evaluation benchmarking.'],
        avoidWhen: ['Time-series data (use TimeSeriesSplit forward-chaining instead to avoid future leakage).'],
        alternatives: ['GroupKFold', 'TimeSeriesSplit'],
      },
      pitfalls: ['Using standard K-Fold on imbalanced classification instead of StratifiedKFold.'],
      playground: {
        title: 'K-Fold Variance Simulator',
        description: 'Adjust fold count K to observe score variance stability.',
        params: [
          { name: 'kFolds', label: 'Fold Count (K)', min: 2, max: 10, step: 1, defaultValue: 5, description: 'Number of cross-validation partitions.' },
        ],
        chartType: 'distribution',
      },
      realProjectCTA: { label: 'Set Up Stratified K-Fold', templateType: 'ML' },
    },
  },
  {
    id: 'ml-evaluation-metrics',
    title: 'ROC-AUC, Confusion Matrix & F1-Score',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'eval_tuning',
    shortSummary: 'Deep evaluation of Precision, Recall, F1, Confusion Matrix, and ROC-AUC curves.',
    icon: '📊',
    tags: ['Metrics', 'ROCAUC', 'ConfusionMatrix', 'F1Score'],
    content: {
      whatItIs: 'Evaluation metrics measure classifier performance across true positives (TP), false positives (FP), true negatives (TN), and false negatives (FN).',
      whyItExists: 'Accuracy alone is misleading on imbalanced data (predicting 99% majority class = 99% accuracy but 0 utility).',
      howItWorks: {
        steps: [
          'Precision = TP / (TP + FP) — "How many predicted positives were actually positive?"',
          'Recall = TP / (TP + FN) — "How many actual positives did we capture?"',
          'F1-Score = Harmonic mean of Precision & Recall.',
          'ROC-AUC: Area under True Positive Rate vs False Positive Rate curve across all thresholds.',
        ],
        mathFormula: 'F_1 = 2 \\cdot \\frac{\\text{Precision} \\cdot \\text{Recall}}{\\text{Precision} + \\text{Recall}}',
        visualDiagramText: '[ Confusion Matrix: TP FP / FN TN ] ➔ [ Compute Precision, Recall, F1 & ROC-AUC ]',
      },
      whenToUse: {
        useCases: ['Fraud detection (recall focused), Spam filtering (precision focused).'],
        avoidWhen: ['Raw uncalibrated regression targets.'],
        alternatives: ['PR-AUC Curve', 'Log Loss'],
      },
      pitfalls: ['Optimizing accuracy on 99:1 imbalanced datasets.'],
      playground: {
        title: 'Precision vs Recall Threshold Simulator',
        description: 'Slide decision boundary to see Precision, Recall, and F1 curve changes.',
        params: [
          { name: 'threshold', label: 'Probability Threshold', min: 0.1, max: 0.9, step: 0.05, defaultValue: 0.5, description: 'Cutoff probability for classification.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Inspect Model Evaluation Metrics', templateType: 'ML' },
    },
  },
  {
    id: 'ml-bias-variance',
    title: 'Bias-Variance Tradeoff',
    category: 'ML',
    difficulty: 'Practitioner',
    stageId: 'eval_tuning',
    shortSummary: 'Balance underfitting (high bias) vs overfitting (high variance) for optimal test error.',
    icon: '🎯',
    tags: ['BiasVariance', 'Underfitting', 'Overfitting', 'Generalization'],
    content: {
      whatItIs: 'The bias-variance tradeoff decomposes expected prediction error into Underfitting (High Bias) and Overfitting (High Variance).',
      whyItExists: 'Understanding this tradeoff guides hyperparameter adjustments — whether to increase model complexity or add regularization.',
      howItWorks: {
        steps: [
          'High Bias: Model too simple (e.g. linear model on complex curve). High train & test error.',
          'High Variance: Model too complex (e.g. depth-20 tree). Low train error, high test error.',
          'Optimal Complexity: Total Error = Bias^2 + Variance + Irreducible Noise.',
        ],
        mathFormula: 'E[(y - \\hat{f})^2] = \\text{Bias}[\\hat{f}]^2 + \\text{Var}[\\hat{f}] + \\sigma^2',
        visualDiagramText: '[ Simple Model (High Bias) ] <--- Optimal Sweet Spot ---> [ Complex Model (High Variance) ]',
      },
      whenToUse: {
        useCases: ['Diagnosing learning curves when model validation score plateaus.'],
        avoidWhen: ['Deep learning regimes where double descent phenomenon occurs.'],
        alternatives: ['Learning Curve Inspection'],
      },
      pitfalls: ['Adding more training data to fix high bias (data helps high variance, not high bias!).'],
      playground: {
        title: 'Model Complexity Error Curve',
        description: 'Adjust complexity parameter to find sweet spot minimizing total error.',
        params: [
          { name: 'complexity', label: 'Model Complexity', min: 1, max: 10, step: 1, defaultValue: 5, description: 'Degree of model parameters.' },
        ],
        chartType: 'regression',
      },
      realProjectCTA: { label: 'Analyze Bias-Variance Curve', templateType: 'ML' },
    },
  },
  {
    id: 'ml-hyperparameter-tuning',
    title: 'Grid, Random & Bayesian Tuning',
    category: 'ML',
    difficulty: 'Expert',
    stageId: 'eval_tuning',
    shortSummary: 'Optimize hyperparameter configurations using GridSearch, RandomSearch, and Bayesian Optimization.',
    icon: '🔮',
    tags: ['GridSearch', 'RandomSearch', 'BayesianOpt', 'Hyperparameters'],
    content: {
      whatItIs: 'Hyperparameter tuning searches the space of model configuration options (learning rate, tree depth, regularization) to find parameters maximizing CV score.',
      whyItExists: 'Default hyperparameter settings are rarely optimal. Proper tuning often boosts accuracy by 5-15%.',
      howItWorks: {
        steps: [
          'Grid Search: Exhaustive brute-force evaluation over predefined parameter grid.',
          'Random Search: Sample parameter space randomly (often finds 95% optimal solution in 1/10th time).',
          'Bayesian Optimization (Optuna/Hyperopt): Build surrogate Gaussian Process model to probabilistically pick best parameters.',
        ],
        visualDiagramText: '[ Grid / Random / Bayesian Sampler ] ➔ Evaluate K-Fold ➔ [ Optimal Parameters ]',
      },
      whenToUse: {
        useCases: ['Final pipeline optimization phase before production deployment.'],
        avoidWhen: ['Initial baseline modeling phase.'],
        alternatives: ['Optuna', 'Hyperopt', 'Ray Tune'],
      },
      pitfalls: ['Tuning hyperparameters on the full dataset without nested cross-validation.'],
      playground: {
        title: 'Search Strategy Efficiency Simulator',
        description: 'Compare trials needed between Grid Search and Bayesian Opt.',
        params: [
          { name: 'trials', label: 'Max Tuning Trials', min: 10, max: 100, step: 10, defaultValue: 30, description: 'Budget of model evaluations.' },
        ],
        chartType: 'regression',
      },
      realProjectCTA: { label: 'Launch Bayesian Tuning Workspace', templateType: 'ML' },
    },
  },
  {
    id: 'ml-kmeans',
    title: 'K-Means & Hierarchical Clustering',
    category: 'ML',
    difficulty: 'Expert',
    stageId: 'advanced',
    shortSummary: 'Partition unlabelled data into K distinct clusters optimizing inertia and centroid distance.',
    icon: '🌌',
    tags: ['KMeans', 'Clustering', 'Unsupervised', 'ElbowMethod'],
    content: {
      whatItIs: 'K-Means is an unsupervised clustering algorithm that partitions data into K spherical clusters centered around centroid points.',
      whyItExists: 'Uncovers hidden customer segments, document groupings, and patterns without ground truth target labels.',
      howItWorks: {
        steps: [
          'Initialize K centroids (K-Means++ initialization).',
          'Assign each data point to nearest centroid (Euclidean distance).',
          'Recompute centroids as mean of assigned points. Repeat until convergence.',
          'Evaluate K using Elbow Method (Inertia) & Silhouette Score.',
        ],
        mathFormula: 'J = \\sum_{i=1}^k \\sum_{x \\in S_i} \\|x - \\mu_i\\|^2',
        visualDiagramText: '[ Random Centroids ] ➔ Reassign Points ➔ [ Converged Cluster Centers ]',
      },
      whenToUse: {
        useCases: ['Customer segmentation, image color quantization, anomaly pre-clustering.'],
        avoidWhen: ['Non-spherical clusters of arbitrary shapes (use DBSCAN instead).'],
        alternatives: ['DBSCAN', 'Gaussian Mixture Models (GMM)'],
      },
      pitfalls: ['Failing to scale features prior to computing cluster distances.'],
      playground: {
        title: 'K-Means Cluster Count (K) Tuner',
        description: 'Adjust K value to inspect centroid locations and Silhouette score.',
        params: [
          { name: 'clustersK', label: 'Clusters (K)', min: 2, max: 8, step: 1, defaultValue: 3, description: 'Number of cluster centroids.' },
        ],
        chartType: 'clustering',
      },
      realProjectCTA: { label: 'Build K-Means Clustering Flow', templateType: 'ML' },
    },
  },
  {
    id: 'ml-dbscan',
    title: 'DBSCAN Density Clustering',
    category: 'ML',
    difficulty: 'Expert',
    stageId: 'advanced',
    shortSummary: 'Density-based clustering finding arbitrary shaped clusters and filtering noise points.',
    icon: '🔬',
    tags: ['DBSCAN', 'Density', 'Anomaly', 'NoisePoints'],
    content: {
      whatItIs: 'DBSCAN (Density-Based Spatial Clustering of Applications with Noise) groups points that are closely packed together, marking sparse region points as noise outliers.',
      whyItExists: 'Unlike K-Means, DBSCAN requires no predefined cluster count K and effortlessly finds complex non-spherical shapes (e.g. concentric rings).',
      howItWorks: {
        steps: [
          'Define radius (epsilon ε) and minimum neighbor count (min_samples).',
          'Core Points: Have at least min_samples within distance ε.',
          'Expand clusters from core points; points outside any ε neighborhood are marked as Noise (-1).',
        ],
        visualDiagramText: '[ Dense Core Regions ] ➔ Expand Neighborhood ➔ [ Complex Shapes + Noise Outliers ]',
      },
      whenToUse: {
        useCases: ['Geospatial GPS trajectory clustering, noise filtering, arbitrary shape discovery.'],
        avoidWhen: ['Datasets with varying density clusters (use HDBSCAN instead).'],
        alternatives: ['HDBSCAN', 'MeanShift'],
      },
      pitfalls: ['Sensitive to epsilon hyperparameter tuning.'],
      playground: {
        title: 'Epsilon (ε) Density Tuner',
        description: 'Adjust epsilon radius to observe noise point detection.',
        params: [
          { name: 'epsilon', label: 'Epsilon Radius (ε)', min: 0.1, max: 2.0, step: 0.1, defaultValue: 0.5, description: 'Distance radius for neighborhood expansion.' },
        ],
        chartType: 'clustering',
      },
      realProjectCTA: { label: 'Deploy DBSCAN Node', templateType: 'ML' },
    },
  },
  {
    id: 'ml-svm',
    title: 'Support Vector Machines (SVM)',
    category: 'ML',
    difficulty: 'Expert',
    stageId: 'advanced',
    shortSummary: 'Maximal margin hyperplanes with RBF kernel trick for complex non-linear classification.',
    icon: '🛡️',
    tags: ['SVM', 'SupportVectors', 'RBFKernel', 'Margin'],
    content: {
      whatItIs: 'SVM finds the optimal decision hyperplane that maximizes the margin distance between opposing class support vectors.',
      whyItExists: 'The Kernel Trick (RBF, Polynomial) projects data into higher dimensions where non-linear datasets become linearly separable.',
      howItWorks: {
        steps: [
          'Identify Support Vectors (closest data points to decision boundary).',
          'Maximize margin 2 / ||w|| subject to zero classification error constraint.',
          'Apply RBF Kernel K(x, y) = exp(-gamma * ||x - y||^2) for curved decision boundaries.',
        ],
        mathFormula: 'K(x, x\') = \\exp(-\\gamma \\|x - x\'\\|^2), \\quad \\min \\frac{1}{2}\\|w\\|^2 + C \\sum \\xi_i',
        visualDiagramText: '[ Non-Linear 2D Data ] ➔ RBF Kernel Projection ➔ [ Linearly Separated Hyperplane ]',
      },
      whenToUse: {
        useCases: ['Small to medium complex datasets, text categorization, bioinformatics.'],
        avoidWhen: ['Large datasets (>100k rows) due to O(N^2) memory scaling.'],
        alternatives: ['Random Forest', 'MLP Neural Network'],
      },
      pitfalls: ['Not scaling features (SVM is extremely distance sensitive).'],
      playground: {
        title: 'SVM Kernel & C Margin Tuner',
        description: 'Adjust C penalty and RBF gamma to observe margin tightness.',
        params: [
          { name: 'costC', label: 'Penalty Cost (C)', min: 0.1, max: 10, step: 0.5, defaultValue: 1.0, description: 'Trades off margin width vs classification accuracy.' },
        ],
        chartType: 'boundary',
      },
      realProjectCTA: { label: 'Build SVM Classifier Pipeline', templateType: 'ML' },
    },
  },
  {
    id: 'ml-pca',
    title: 'Principal Component Analysis (PCA)',
    category: 'ML',
    difficulty: 'Expert',
    stageId: 'advanced',
    shortSummary: 'Linear dimensionality reduction projecting data onto orthogonal maximum-variance axes.',
    icon: '📐',
    tags: ['PCA', 'Eigenvectors', 'DimensionalityReduction', 'Variance'],
    content: {
      whatItIs: 'PCA compresses high-dimensional data into a lower-dimensional subspace while retaining maximum feature variance.',
      whyItExists: 'Mitigates the Curse of Dimensionality, removes collinearity, speeds up downstream model training, and enables 2D/3D visualization.',
      howItWorks: {
        steps: [
          'Standardize features to zero mean.',
          'Compute covariance matrix C = (X^T X) / (n-1).',
          'Calculate Eigenvalues and Eigenvectors of covariance matrix.',
          'Project data onto top K eigenvectors capturing 90-95% cumulative variance.',
        ],
        mathFormula: 'C v = \\lambda v, \\quad X_{\\text{pca}} = X V_k',
        visualDiagramText: '[ 50 Feature Columns ] ➔ PCA Projection ➔ [ 3 Principal Components (92% Var) ]',
      },
      whenToUse: {
        useCases: ['Dimensionality reduction, image compression, financial factor modeling.'],
        avoidWhen: ['When raw feature interpretability is required by business stakeholders.'],
        alternatives: ['t-SNE', 'UMAP', 'TruncatedSVD'],
      },
      pitfalls: ['Failing to standardize features before computing covariance.'],
      playground: {
        title: 'Explained Variance Ratio Simulator',
        description: 'Adjust component count K to inspect cumulative variance percentage.',
        params: [
          { name: 'nComponents', label: 'Components (K)', min: 1, max: 10, step: 1, defaultValue: 2, description: 'Number of principal axes kept.' },
        ],
        chartType: 'distribution',
      },
      realProjectCTA: { label: 'Apply PCA Node in Workspace', templateType: 'ML' },
    },
  },
];
