import type {
  Project,
  DatasetItem,
  KaggleDatasetPlaceholder,
  LearningModule,
  UserProfile,
  CanvasNodeData,
} from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Customer Churn Prediction v3.1',
    type: 'ML',
    description: 'Binary classification to predict telecom customer attrition.',
    datasetName: 'churn_data_preprocessed.csv',
    lastModified: '2 mins ago',
    status: 'In Progress',
    isFavorite: true,
    accuracy: '86%',
    nodesCount: 6,
  },
  {
    id: 'proj-2',
    name: 'E-commerce EDA & Segmentation',
    type: 'EDA',
    description: 'Exploratory correlation and cluster analysis on customer purchasing behavior.',
    datasetName: 'ecommerce_behavior.csv',
    lastModified: '1 hour ago',
    status: 'Completed',
    isFavorite: true,
    nodesCount: 5,
  },
  {
    id: 'proj-3',
    name: 'ResNet Image Classifier',
    type: 'DL',
    description: 'Deep Convolutional Neural Network for image feature extraction.',
    datasetName: 'cifar_subset.parquet',
    lastModified: 'Yesterday',
    status: 'Draft',
    isFavorite: false,
    accuracy: '92.4%',
    nodesCount: 8,
  },
  {
    id: 'proj-4',
    name: 'House Prices Regression',
    type: 'ML',
    description: 'Predicting real estate prices with gradient boosted trees.',
    datasetName: 'housing_features.csv',
    lastModified: '3 days ago',
    status: 'Completed',
    isFavorite: false,
    accuracy: '89.1%',
    nodesCount: 5,
  },
];

export const MOCK_DATASETS: DatasetItem[] = [
  {
    id: 'ds-1',
    name: 'churn_data_preprocessed.csv',
    rows: 10000,
    columns: 14,
    size: '1.2 MB',
    uploadedAt: '2026-08-10',
    source: 'Upload',
    format: 'CSV',
  },
  {
    id: 'ds-2',
    name: 'ecommerce_behavior.csv',
    rows: 45000,
    columns: 22,
    size: '4.8 MB',
    uploadedAt: '2026-08-11',
    source: 'Upload',
    format: 'CSV',
  },
  {
    id: 'ds-3',
    name: 'housing_features.csv',
    rows: 1460,
    columns: 81,
    size: '460 KB',
    uploadedAt: '2026-08-12',
    source: 'Kaggle',
    format: 'CSV',
  },
  {
    id: 'ds-4',
    name: 'cifar_subset.parquet',
    rows: 5000,
    columns: 3,
    size: '12.4 MB',
    uploadedAt: '2026-08-13',
    source: 'Sample',
    format: 'Parquet',
  },
];

export const MOCK_KAGGLE_DATASETS: KaggleDatasetPlaceholder[] = [
  {
    id: 'k-1',
    title: 'Titanic - Machine Learning from Disaster',
    downloads: '1.2M',
    usability: '10.0',
    size: '60 KB',
    tags: ['Classification', 'Tabular', 'Beginner'],
  },
  {
    id: 'k-2',
    title: 'Credit Card Fraud Detection',
    downloads: '540K',
    usability: '9.4',
    size: '66 MB',
    tags: ['Imbalanced Data', 'Anomaly Detection'],
  },
  {
    id: 'k-3',
    title: 'Global Climate Change Temperature Data',
    downloads: '310K',
    usability: '8.8',
    size: '18 MB',
    tags: ['Time Series', 'EDA', 'Environment'],
  },
];

export const MOCK_EDA_MODULES: LearningModule[] = [
  {
    id: 'eda-1',
    title: 'Data Hygiene & Missing Value Analysis',
    category: 'EDA',
    summary: 'Identify missing patterns, null ratios, and strategies for mean/median/KNN imputation.',
    difficulty: 'Beginner',
    estimatedMinutes: 12,
    icon: 'clean',
    topics: ['Missing Matrix', 'Heatmaps', 'Imputation'],
  },
  {
    id: 'eda-2',
    title: 'Feature Distributions & Outlier Detection',
    category: 'EDA',
    summary: 'Analyze skewness, kurtosis, Boxplots, IQR bounds, and Z-score transformations.',
    difficulty: 'Intermediate',
    estimatedMinutes: 15,
    icon: 'chart',
    topics: ['Histograms', 'Boxplots', 'Z-Score'],
  },
  {
    id: 'eda-3',
    title: 'Correlation Matrix & Pairwise Interactions',
    category: 'EDA',
    summary: 'Compute Pearson & Spearman rank correlations to spot multi-collinearity.',
    difficulty: 'Intermediate',
    estimatedMinutes: 18,
    icon: 'grid',
    topics: ['Pearson', 'Collinearity', 'Scatter Matrix'],
  },
];

export const MOCK_ML_MODULES: LearningModule[] = [
  {
    id: 'ml-1',
    title: 'Classification Fundamentals',
    category: 'ML',
    summary: 'Understand Logistic Regression, Decision Trees, Random Forests, and XGBoost.',
    difficulty: 'Beginner',
    estimatedMinutes: 20,
    icon: 'tree',
    topics: ['Decision Trees', 'Random Forest', 'XGBoost'],
  },
  {
    id: 'ml-2',
    title: 'Hyperparameter Tuning & Cross-Validation',
    category: 'ML',
    summary: 'Master Grid Search, Random Search, and Bayesian Optimization with K-Fold CV.',
    difficulty: 'Intermediate',
    estimatedMinutes: 25,
    icon: 'tune',
    topics: ['GridSearchCV', 'K-Fold CV', 'Bayesian'],
  },
  {
    id: 'ml-3',
    title: 'Model Evaluation Metrics',
    category: 'ML',
    summary: 'Deep dive into Confusion Matrix, Precision, Recall, F1-Score, and ROC-AUC curves.',
    difficulty: 'Intermediate',
    estimatedMinutes: 15,
    icon: 'eval',
    topics: ['ROC-AUC', 'F1-Score', 'Precision-Recall'],
  },
];

export const MOCK_DL_MODULES: LearningModule[] = [
  {
    id: 'dl-1',
    title: 'Perceptron & Multi-Layer Perceptrons (MLP)',
    category: 'DL',
    summary: 'Building blocks of neural networks: Activation functions, Forward Pass & Backprop.',
    difficulty: 'Intermediate',
    estimatedMinutes: 30,
    icon: 'network',
    topics: ['Backpropagation', 'ReLU/Sigmoid', 'Loss Functions'],
  },
  {
    id: 'dl-2',
    title: 'Convolutional Neural Networks (CNN)',
    category: 'DL',
    summary: 'Filters, Stride, Padding, Pooling, and CNN Architectures like ResNet & VGG.',
    difficulty: 'Advanced',
    estimatedMinutes: 35,
    icon: 'layers',
    topics: ['Conv2D', 'MaxPooling', 'ResNet'],
  },
  {
    id: 'dl-3',
    title: 'Optimization Algorithms & Learning Rates',
    category: 'DL',
    summary: 'Compare SGD, Adam, AdamW, RMSprop, and learning rate schedulers.',
    difficulty: 'Advanced',
    estimatedMinutes: 25,
    icon: 'zap',
    topics: ['Adam Optimizer', 'Learning Rate Decay', 'Batch Norm'],
  },
];

export const MOCK_STARTER_NODES: Record<'EDA' | 'ML' | 'DL', CanvasNodeData[]> = {
  EDA: [
    { id: 'n-1', title: 'Dataset Input', subtitle: 'churn_data.csv', type: 'input', x: 80, y: 150 },
    { id: 'n-2', title: 'Missing Value Analyzer', subtitle: 'Null Ratio & Matrix', type: 'preprocessing', x: 280, y: 150 },
    { id: 'n-3', title: 'Distribution Profiler', subtitle: 'Histograms & Boxplots', type: 'eval', x: 480, y: 150 },
  ],
  ML: [
    { id: 'n-1', title: 'Dataset (Input)', subtitle: 'churn_data.csv', type: 'input', x: 40, y: 180 },
    { id: 'n-2', title: 'Preprocessing', subtitle: 'Cleaner & Scaler', type: 'preprocessing', x: 180, y: 180 },
    { id: 'n-3', title: 'Train/Test Split', subtitle: '80/20 Stratified', type: 'preprocessing', x: 320, y: 180 },
    { id: 'n-4', title: 'Random Forest Classifier', subtitle: '(Selected)', type: 'model', x: 500, y: 80, status: 'selected' },
    { id: 'n-5', title: 'XGBoost Classifier', subtitle: 'Gradient Boosted', type: 'model', x: 500, y: 180 },
    { id: 'n-6', title: 'Support Vector Machine', subtitle: 'RBF Kernel', type: 'model', x: 500, y: 280 },
    { id: 'n-7', title: 'Evaluation', subtitle: 'F1, AUC, Acc', type: 'eval', x: 700, y: 180 },
  ],
  DL: [
    { id: 'n-1', title: 'Image Dataset', subtitle: 'cifar_subset.parquet', type: 'input', x: 60, y: 160 },
    { id: 'n-2', title: 'Conv2D Layer (32)', subtitle: 'Kernel 3x3, ReLU', type: 'model', x: 240, y: 160 },
    { id: 'n-3', title: 'MaxPooling2D', subtitle: 'Pool 2x2', type: 'preprocessing', x: 420, y: 160 },
    { id: 'n-4', title: 'Dense FC Layer', subtitle: '128 Neurons', type: 'model', x: 600, y: 160 },
    { id: 'n-5', title: 'Loss & Accuracy', subtitle: 'CrossEntropy', type: 'eval', x: 780, y: 160 },
  ],
};

export const MOCK_USER_PROFILE: UserProfile = {
  name: 'Alex Kumar',
  handle: '@alexkumar_ml',
  role: 'Senior Machine Learning Engineer',
  avatar: 'AK',
  bio: 'Building no-code visual pipelines & deep learning architectures. Passionate about AutoML and model interpretability.',
  location: 'Bengaluru, India',
  joinedDate: 'January 2025',
  completedProjects: 14,
  totalModelsTrained: 86,
  topAccuracy: '94.2%',
  skills: [
    { name: 'Scikit-Learn', level: 95 },
    { name: 'PyTorch & Deep Learning', level: 88 },
    { name: 'Data Preprocessing & EDA', level: 92 },
    { name: 'XGBoost & Ensembles', level: 90 },
    { name: 'Pipeline Design (n8n style)', level: 85 },
  ],
  achievements: [
    {
      title: 'AutoML Master',
      desc: 'Trained and evaluated over 50 automated ML pipelines.',
      date: 'Aug 2026',
      icon: '🏆',
    },
    {
      title: 'Precision Specialist',
      desc: 'Achieved >94% top accuracy on complex churn prediction datasets.',
      date: 'Jul 2026',
      icon: '⚡',
    },
    {
      title: 'Visual Workflow Pioneer',
      desc: 'Designed 10+ end-to-end visual canvas templates.',
      date: 'May 2026',
      icon: '🎨',
    },
  ],
};
